[package]
name = "panic_unwind"
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/rust.git"
description = "Implementation of Rust panics via stack unwinding"
edition = "2018"

[lib]
test = false
bench = false
doc = false

[dependencies]
alloc = { path = "../alloc" }
core = { path = "../core" }
libc = { version = "0.2", default-features = false, git = "https://github.com/MabezDev/libc", branch = "esp-idf-stat-types" }
unwind = { path = "../unwind" }
compiler_builtins = "0.1.0"
cfg-if = "0.1.8"
